<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 dplyr - A brief introduction to tidy data manipulation | Intro to R for Forest Ecosystem Science</title>
  <meta name="description" content="Introductory R" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 dplyr - A brief introduction to tidy data manipulation | Intro to R for Forest Ecosystem Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Introductory R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 dplyr - A brief introduction to tidy data manipulation | Intro to R for Forest Ecosystem Science" />
  
  <meta name="twitter:description" content="Introductory R" />
  

<meta name="author" content="Anu Singh, Benjamin Wagner, and Kaitlyn Hammond" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducing-the-koala-dataset.html"/>
<link rel="next" href="introduction-to-data-visualization-in-ggplot2.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>1.1</b> Disclaimer</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html"><a href="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html"><i class="fa fa-check"></i><b>2</b> A few words on a productive setup and workflow in <code>R</code> with <em>R-Studio</em></a><ul>
<li class="chapter" data-level="2.1" data-path="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html"><a href="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html#r-projects"><i class="fa fa-check"></i><b>2.1</b> R Projects</a></li>
<li class="chapter" data-level="2.2" data-path="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html"><a href="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html#setting-up-the-r-studio-user-interface"><i class="fa fa-check"></i><b>2.2</b> Setting up the R-Studio User interface</a></li>
<li class="chapter" data-level="2.3" data-path="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html"><a href="a-few-words-on-a-productive-setup-and-workflow-in-r-with-r-studio.html#code-folds-and-commenting"><i class="fa fa-check"></i><b>2.3</b> Code folds and commenting</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html"><i class="fa fa-check"></i><b>3</b> Introducing the koala dataset</a><ul>
<li class="chapter" data-level="3.1" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html#data-types-and-variable-types"><i class="fa fa-check"></i><b>3.1</b> <em>data types</em> and <em>variable types</em></a></li>
<li class="chapter" data-level="3.2" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html#changing-variable-types"><i class="fa fa-check"></i><b>3.2</b> Changing <em>variable types</em></a></li>
<li class="chapter" data-level="3.3" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html#how-the-koala-dataset-was-collated"><i class="fa fa-check"></i><b>3.3</b> How the koala dataset was collated</a><ul>
<li class="chapter" data-level="3.3.1" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html#loading-the-raw-data"><i class="fa fa-check"></i><b>3.3.1</b> Loading the raw data</a></li>
<li class="chapter" data-level="3.3.2" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html#adding-the-state-names-by-location"><i class="fa fa-check"></i><b>3.3.2</b> Adding the state names by location</a></li>
<li class="chapter" data-level="3.3.3" data-path="introducing-the-koala-dataset.html"><a href="introducing-the-koala-dataset.html#creating-dummy-data"><i class="fa fa-check"></i><b>3.3.3</b> Creating dummy data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><i class="fa fa-check"></i><b>4</b> <code>dplyr</code> - A brief introduction to tidy data manipulation</a><ul>
<li class="chapter" data-level="4.1" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#loading-and-checking-the-data"><i class="fa fa-check"></i><b>4.1</b> Loading and checking the data</a></li>
<li class="chapter" data-level="4.2" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#working-with-dplyr"><i class="fa fa-check"></i><b>4.2</b> Working with <code>dplyr</code></a><ul>
<li class="chapter" data-level="4.2.1" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#select-and-dplyrs-pipe"><i class="fa fa-check"></i><b>4.2.1</b> select() and dplyr’s pipe</a></li>
<li class="chapter" data-level="4.2.2" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#filter"><i class="fa fa-check"></i><b>4.2.2</b> filter()</a></li>
<li class="chapter" data-level="4.2.3" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#challenge-1"><i class="fa fa-check"></i><b>4.2.3</b> Challenge 1</a></li>
<li class="chapter" data-level="4.2.4" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#group_by-and-summarise"><i class="fa fa-check"></i><b>4.2.4</b> group_by() and summarise()</a></li>
<li class="chapter" data-level="4.2.5" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#challenge-2"><i class="fa fa-check"></i><b>4.2.5</b> Challenge 2</a></li>
<li class="chapter" data-level="4.2.6" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#mutate"><i class="fa fa-check"></i><b>4.2.6</b> mutate()</a></li>
<li class="chapter" data-level="4.2.7" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#challenge-3"><i class="fa fa-check"></i><b>4.2.7</b> Challenge 3</a></li>
<li class="chapter" data-level="4.2.8" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#pivoting"><i class="fa fa-check"></i><b>4.2.8</b> Pivoting</a></li>
<li class="chapter" data-level="4.2.9" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#challenge-4"><i class="fa fa-check"></i><b>4.2.9</b> Challenge 4</a></li>
<li class="chapter" data-level="4.2.10" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#challenge-5"><i class="fa fa-check"></i><b>4.2.10</b> Challenge 5</a></li>
<li class="chapter" data-level="4.2.11" data-path="dplyr-a-brief-introduction-to-tidy-data-manipulation.html"><a href="dplyr-a-brief-introduction-to-tidy-data-manipulation.html#solution-to-all-challenges"><i class="fa fa-check"></i><b>4.2.11</b> Solution to all challenges</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="introduction-to-data-visualization-in-ggplot2.html"><a href="introduction-to-data-visualization-in-ggplot2.html"><i class="fa fa-check"></i><b>5</b> Introduction to data visualization in <code>ggplot2</code></a></li>
<li class="chapter" data-level="6" data-path="introduction-to-linear-models-in-r.html"><a href="introduction-to-linear-models-in-r.html"><i class="fa fa-check"></i><b>6</b> Introduction to linear models in R</a></li>
<li class="chapter" data-level="7" data-path="functions-in-r.html"><a href="functions-in-r.html"><i class="fa fa-check"></i><b>7</b> Functions in R</a><ul>
<li class="chapter" data-level="7.1" data-path="functions-in-r.html"><a href="functions-in-r.html#introduction-1"><i class="fa fa-check"></i><b>7.1</b> Introduction</a><ul>
<li class="chapter" data-level="7.1.1" data-path="functions-in-r.html"><a href="functions-in-r.html#mathematical-operations"><i class="fa fa-check"></i><b>7.1.1</b> Mathematical operations</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="functions-in-r.html"><a href="functions-in-r.html#what-is-an-r-function"><i class="fa fa-check"></i><b>7.2</b> What is an R function?</a></li>
<li class="chapter" data-level="7.3" data-path="functions-in-r.html"><a href="functions-in-r.html#nesting-functions"><i class="fa fa-check"></i><b>7.3</b> Nesting functions</a><ul>
<li class="chapter" data-level="7.3.1" data-path="functions-in-r.html"><a href="functions-in-r.html#some-basic-built-in-mathematical-functions"><i class="fa fa-check"></i><b>7.3.1</b> Some basic built-in mathematical functions</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="functions-in-r.html"><a href="functions-in-r.html#assigning-variables-within-functions"><i class="fa fa-check"></i><b>7.4</b> Assigning variables within functions</a></li>
<li class="chapter" data-level="7.5" data-path="functions-in-r.html"><a href="functions-in-r.html#challenge-1-2"><i class="fa fa-check"></i><b>7.5</b> Challenge 1</a></li>
<li class="chapter" data-level="7.6" data-path="functions-in-r.html"><a href="functions-in-r.html#using-return"><i class="fa fa-check"></i><b>7.6</b> Using <code>return()</code></a></li>
<li class="chapter" data-level="7.7" data-path="functions-in-r.html"><a href="functions-in-r.html#challenge-2-2"><i class="fa fa-check"></i><b>7.7</b> Challenge 2</a></li>
<li class="chapter" data-level="7.8" data-path="functions-in-r.html"><a href="functions-in-r.html#solutions-to-challenges"><i class="fa fa-check"></i><b>7.8</b> Solutions to challenges</a><ul>
<li class="chapter" data-level="7.8.1" data-path="functions-in-r.html"><a href="functions-in-r.html#challenge-1-3"><i class="fa fa-check"></i><b>7.8.1</b> Challenge 1</a></li>
<li class="chapter" data-level="7.8.2" data-path="functions-in-r.html"><a href="functions-in-r.html#challenge-2-3"><i class="fa fa-check"></i><b>7.8.2</b> Challenge 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html"><i class="fa fa-check"></i><b>8</b> Working with spatial data in <code>R</code></a><ul>
<li class="chapter" data-level="8.1" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#transforming-a-dataset-into-an-sf-object"><i class="fa fa-check"></i><b>8.1</b> Transforming a dataset into an <code>sf</code> object</a></li>
<li class="chapter" data-level="8.2" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#loading-shapefiles-into-r-transforming-and-plotting"><i class="fa fa-check"></i><b>8.2</b> Loading shapefiles into <code>R</code>, transforming and plotting</a><ul>
<li class="chapter" data-level="8.2.1" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#challenge-1-4"><i class="fa fa-check"></i><b>8.2.1</b> Challenge 1</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#simple-geometric-operations"><i class="fa fa-check"></i><b>8.3</b> Simple geometric operations</a></li>
<li class="chapter" data-level="8.4" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#making-a-map-using-ggplot2"><i class="fa fa-check"></i><b>8.4</b> Making a map using <code>ggplot2</code></a><ul>
<li class="chapter" data-level="8.4.1" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#challenge-2-4"><i class="fa fa-check"></i><b>8.4.1</b> Challenge 2</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#r-raster-basics"><i class="fa fa-check"></i><b>8.5</b> <code>R</code> raster basics</a></li>
<li class="chapter" data-level="8.6" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#plotting-rasters-in-ggplot2"><i class="fa fa-check"></i><b>8.6</b> Plotting rasters in <code>ggplot2</code></a><ul>
<li class="chapter" data-level="8.6.1" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#challenge-3-2"><i class="fa fa-check"></i><b>8.6.1</b> Challenge 3</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#solutions-to-challenges-1"><i class="fa fa-check"></i><b>8.7</b> Solutions to Challenges</a><ul>
<li class="chapter" data-level="8.7.1" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#challenge-1-5"><i class="fa fa-check"></i><b>8.7.1</b> Challenge 1</a></li>
<li class="chapter" data-level="8.7.2" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#challenge-2-5"><i class="fa fa-check"></i><b>8.7.2</b> Challenge 2</a></li>
<li class="chapter" data-level="8.7.3" data-path="working-with-spatial-data-in-r.html"><a href="working-with-spatial-data-in-r.html#challenge-3-3"><i class="fa fa-check"></i><b>8.7.3</b> Challenge 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html"><i class="fa fa-check"></i><b>9</b> Spatial tools for forestry and ecological applications</a><ul>
<li class="chapter" data-level="9.1" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#an-introduction-to-processing-lidar-data-in-r"><i class="fa fa-check"></i><b>9.1</b> An introduction to processing LiDAR data in <code>R</code></a></li>
<li class="chapter" data-level="9.2" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#working-with-lidar-data-in-r"><i class="fa fa-check"></i><b>9.2</b> Working with LiDAR data in R</a></li>
<li class="chapter" data-level="9.3" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#step-1.-loading-and-visualizing-pointclouds"><i class="fa fa-check"></i><b>9.3</b> Step 1. Loading and visualizing pointclouds</a></li>
<li class="chapter" data-level="9.4" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#step-2.-computing-a-canopy-height-model"><i class="fa fa-check"></i><b>9.4</b> Step 2. Computing a canopy height model</a><ul>
<li class="chapter" data-level="9.4.1" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#ground-detection-and-normalizing-a-point-cloud"><i class="fa fa-check"></i><b>9.4.1</b> Ground detection and normalizing a point cloud</a></li>
<li class="chapter" data-level="9.4.2" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#building-the-initial-chm"><i class="fa fa-check"></i><b>9.4.2</b> Building the initial CHM</a></li>
<li class="chapter" data-level="9.4.3" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#challenge-1-6"><i class="fa fa-check"></i><b>9.4.3</b> Challenge 1</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#step-3.-individual-tree-segmentation"><i class="fa fa-check"></i><b>9.5</b> Step 3. Individual tree segmentation</a><ul>
<li class="chapter" data-level="9.5.1" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#delineating-the-crowns"><i class="fa fa-check"></i><b>9.5.1</b> Delineating the crowns</a></li>
<li class="chapter" data-level="9.5.2" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#challenge-2-6"><i class="fa fa-check"></i><b>9.5.2</b> Challenge 2</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#additional-analysis-computing-a-digital-terrain-model-dtm"><i class="fa fa-check"></i><b>9.6</b> Additional analysis: Computing a digital terrain model (DTM)</a><ul>
<li class="chapter" data-level="9.6.1" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#challenge-3-4"><i class="fa fa-check"></i><b>9.6.1</b> Challenge 3</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#wrapping-up"><i class="fa fa-check"></i><b>9.7</b> Wrapping up</a></li>
<li class="chapter" data-level="9.8" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#solutions-to-the-challenges"><i class="fa fa-check"></i><b>9.8</b> Solutions to the challenges</a><ul>
<li class="chapter" data-level="9.8.1" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#challenge-1-7"><i class="fa fa-check"></i><b>9.8.1</b> Challenge 1</a></li>
<li class="chapter" data-level="9.8.2" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#challenge-2-7"><i class="fa fa-check"></i><b>9.8.2</b> Challenge 2</a></li>
<li class="chapter" data-level="9.8.3" data-path="spatial-tools-for-forestry-and-ecological-applications.html"><a href="spatial-tools-for-forestry-and-ecological-applications.html#challenge-3-5"><i class="fa fa-check"></i><b>9.8.3</b> Challenge 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><a href="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><i class="fa fa-check"></i><b>10</b> Extracting raster fractions and area using a polygon mask</a><ul>
<li class="chapter" data-level="10.1" data-path="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><a href="extracting-raster-fractions-and-area-using-a-polygon-mask.html#problem-statement"><i class="fa fa-check"></i><b>10.1</b> Problem statement</a></li>
<li class="chapter" data-level="10.2" data-path="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><a href="extracting-raster-fractions-and-area-using-a-polygon-mask.html#creating-some-dummy-raster-data"><i class="fa fa-check"></i><b>10.2</b> Creating some dummy raster data</a></li>
<li class="chapter" data-level="10.3" data-path="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><a href="extracting-raster-fractions-and-area-using-a-polygon-mask.html#create-some-reserves"><i class="fa fa-check"></i><b>10.3</b> Create some reserves</a></li>
<li class="chapter" data-level="10.4" data-path="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><a href="extracting-raster-fractions-and-area-using-a-polygon-mask.html#extracting-data"><i class="fa fa-check"></i><b>10.4</b> Extracting data</a></li>
<li class="chapter" data-level="10.5" data-path="extracting-raster-fractions-and-area-using-a-polygon-mask.html"><a href="extracting-raster-fractions-and-area-using-a-polygon-mask.html#plotting-the-results"><i class="fa fa-check"></i><b>10.5</b> Plotting the results</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="calculating-class-area-from-raster.html"><a href="calculating-class-area-from-raster.html"><i class="fa fa-check"></i><b>11</b> Calculating class area from raster</a><ul>
<li class="chapter" data-level="11.1" data-path="calculating-class-area-from-raster.html"><a href="calculating-class-area-from-raster.html#simple-area-and-area-fraction-calculations-on-a-classified-raster"><i class="fa fa-check"></i><b>11.1</b> Simple area and area fraction calculations on a classified raster</a><ul>
<li class="chapter" data-level="11.1.1" data-path="calculating-class-area-from-raster.html"><a href="calculating-class-area-from-raster.html#creating-dummy-data-1"><i class="fa fa-check"></i><b>11.1.1</b> Creating dummy data</a></li>
<li class="chapter" data-level="11.1.2" data-path="calculating-class-area-from-raster.html"><a href="calculating-class-area-from-raster.html#preparing-the-raster-for-area-calculation"><i class="fa fa-check"></i><b>11.1.2</b> Preparing the raster for area calculation</a></li>
<li class="chapter" data-level="11.1.3" data-path="calculating-class-area-from-raster.html"><a href="calculating-class-area-from-raster.html#compiling-a-comprehensive-table"><i class="fa fa-check"></i><b>11.1.3</b> Compiling a comprehensive table</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Intro to R for Forest Ecosystem Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="dplyr---a-brief-introduction-to-tidy-data-manipulation" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> <code>dplyr</code> - A brief introduction to tidy data manipulation</h1>
<p><img src="data/dplyr-doc/dplyr.png" width="250" style="display: block; margin: auto;" /></p>
<div id="loading-and-checking-the-data" class="section level2">
<h2><span class="header-section-number">4.1</span> Loading and checking the data</h2>
<p>We will work with our koala dataset. You can download it <a href="https://www.dropbox.com/s/1zhru8ui3btmg0n/koala.csv?dl=1">here</a>. Furthermore you need to install the <code>tidyverse</code> package, which contains <code>dplyr</code>.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" title="1"><span class="kw">install.packages</span>(<span class="st">&#39;tidyverse&#39;</span>)</a></code></pre></div>
<p>First we need to load the dataset we’re working with.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1">koala&lt;-<span class="kw">read.csv</span>(<span class="st">&#39;data/koala.csv&#39;</span>)</a></code></pre></div>
<p>It should contain the following columns:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" title="1"><span class="kw">names</span>(koala)</a></code></pre></div>
<pre><code>##  [1] &quot;species&quot; &quot;X&quot;       &quot;Y&quot;       &quot;state&quot;   &quot;region&quot;  &quot;sex&quot;     &quot;weight&quot; 
##  [8] &quot;size&quot;    &quot;fur&quot;     &quot;tail&quot;    &quot;age&quot;     &quot;color&quot;   &quot;joey&quot;    &quot;behav&quot;  
## [15] &quot;obs&quot;</code></pre>
<p>Lets look at a structure and summary of this dataset:</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1"><span class="kw">str</span>(koala)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    242 obs. of  15 variables:
##  $ species: Factor w/ 1 level &quot;Phascolarctos cinereus&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ X      : num  153 148 153 153 153 ...
##  $ Y      : num  -27.5 -22.5 -27.5 -27.5 -27.5 ...
##  $ state  : Factor w/ 4 levels &quot;New South Wales&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ region : Factor w/ 2 levels &quot;northern&quot;,&quot;southern&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ sex    : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 2 1 2 2 1 2 2 2 1 1 ...
##  $ weight : num  7.12 5.45 6.63 6.47 5.62 ...
##  $ size   : num  70.8 70.4 68.7 73 65.2 ...
##  $ fur    : num  1.86 1.85 2.48 1.92 1.95 ...
##  $ tail   : num  1.17 1.56 1.06 1.8 1.63 ...
##  $ age    : int  8 10 1 1 10 12 9 1 1 1 ...
##  $ color  : Factor w/ 6 levels &quot;chocolate brown&quot;,..: 3 4 6 3 4 4 6 4 3 3 ...
##  $ joey   : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 1 2 1 1 1 1 1 1 1 1 ...
##  $ behav  : Factor w/ 3 levels &quot;Feeding&quot;,&quot;Just Chillin&quot;,..: 3 3 2 3 3 1 2 3 1 3 ...
##  $ obs    : Factor w/ 3 levels &quot;Opportunistic&quot;,..: 2 1 2 3 3 1 3 2 2 2 ...</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="kw">summary</span>(koala)</a></code></pre></div>
<pre><code>##                    species          X               Y         
##  Phascolarctos cinereus:242   Min.   :138.6   Min.   :-39.00  
##                               1st Qu.:150.0   1st Qu.:-34.49  
##                               Median :152.0   Median :-32.67  
##                               Mean   :150.3   Mean   :-32.36  
##                               3rd Qu.:152.9   3rd Qu.:-30.31  
##                               Max.   :153.6   Max.   :-21.39  
##              state          region        sex          weight      
##  New South Wales:181   northern:165   female:127   Min.   : 5.406  
##  Queensland     : 16   southern: 77   male  :115   1st Qu.: 6.574  
##  South Australia: 14                               Median : 7.277  
##  Victoria       : 31                               Mean   : 7.923  
##                                                    3rd Qu.: 8.765  
##                                                    Max.   :17.889  
##       size            fur             tail            age       
##  Min.   :64.81   Min.   :1.110   Min.   :1.004   Min.   : 1.00  
##  1st Qu.:68.43   1st Qu.:2.410   1st Qu.:1.272   1st Qu.: 3.00  
##  Median :70.27   Median :2.797   Median :1.534   Median : 7.00  
##  Mean   :70.94   Mean   :2.896   Mean   :1.507   Mean   : 6.43  
##  3rd Qu.:72.33   3rd Qu.:3.217   3rd Qu.:1.750   3rd Qu.: 9.00  
##  Max.   :81.91   Max.   :5.876   Max.   :1.981   Max.   :12.00  
##              color     joey              behav                obs    
##  chocolate brown:21   No :185   Feeding     : 48   Opportunistic:65  
##  dark grey      :36   Yes: 57   Just Chillin: 67   Spotlighting :94  
##  grey           :69             Sleeping    :127   Stagwatching :83  
##  grey-brown     :53                                                  
##  light brown    :20                                                  
##  light grey     :43</code></pre>
<p>This dataset contains the positions of each koala in Latitude and Longitude (<code>X</code> and <code>Y</code>) as well as variables describing their physiology, behavior and how they were recorded. It’s typical presence-only wildlife data, combining observations with some data describing each individual, which could e.g. be used for distribution modeling or to test influences of other variables such as climate on behavior and physiology of this particular species. You can read more about the dataset and typical <code>R</code> data types in the separate koala dataset tutorial, which will introduce you to the data and explain <code>R</code> data and variable types.</p>
<p>Often in these types of studies, we are not interested in all the recorded variables and thus first need to ‘clean’ our data to make it easier to work with it. <code>dplyr</code> is a package designed to make data ‘cleaning’ and manipulation of large datasets easier by introducing specific syntax. Let’s see how it works and compares to base <code>R</code> functionality!</p>
</div>
<div id="working-with-dplyr" class="section level2">
<h2><span class="header-section-number">4.2</span> Working with <code>dplyr</code></h2>
<p>Base <code>R</code> sub-setting can be very tedious. Imagine we want to got the mean age for our koalas, but split it by sex. Getting one mean is easy:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1"><span class="kw">mean</span>(koala[koala<span class="op">$</span>sex <span class="op">==</span><span class="st"> &#39;male&#39;</span>, <span class="st">&quot;age&quot;</span>],<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## [1] 6.626087</code></pre>
<p>Summarizing both sexes and saving it in a table takes a few lines of code:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1">female_mean&lt;-<span class="kw">mean</span>(koala[koala<span class="op">$</span>sex <span class="op">==</span><span class="st"> &#39;female&#39;</span>, <span class="st">&quot;age&quot;</span>],<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb79-2" title="2"></a>
<a class="sourceLine" id="cb79-3" title="3">male_mean&lt;-<span class="kw">mean</span>(koala[koala<span class="op">$</span>sex <span class="op">==</span><span class="st"> &#39;male&#39;</span>, <span class="st">&quot;age&quot;</span>],<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb79-4" title="4"></a>
<a class="sourceLine" id="cb79-5" title="5">means&lt;-<span class="kw">rbind</span>(<span class="kw">c</span>(female_mean, male_mean))</a>
<a class="sourceLine" id="cb79-6" title="6"></a>
<a class="sourceLine" id="cb79-7" title="7">means&lt;-<span class="kw">as.data.frame</span>(means)</a>
<a class="sourceLine" id="cb79-8" title="8"></a>
<a class="sourceLine" id="cb79-9" title="9"><span class="kw">names</span>(means)&lt;-<span class="kw">c</span>(<span class="st">&#39;female&#39;</span>, <span class="st">&#39;male&#39;</span>)</a></code></pre></div>
<p>Lets have a look at the results.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1">means</a></code></pre></div>
<pre><code>##     female     male
## 1 6.251969 6.626087</code></pre>
<p>That’s all good, but with that many lines of code quite error prone … <code>dplyr</code> makes data manipulation simpler. For this example, we would only require one line of code!</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb82-2" title="2"></a>
<a class="sourceLine" id="cb82-3" title="3">mean_age_koala&lt;-koala<span class="op">%&gt;%</span><span class="kw">group_by</span>(sex)<span class="op">%&gt;%</span><span class="kw">summarise</span>(<span class="dt">mean_age =</span> <span class="kw">mean</span>(age))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   sex    mean_age
##   &lt;fct&gt;     &lt;dbl&gt;
## 1 female     6.25
## 2 male       6.63</code></pre>
<p>So simple, and looks even better than our base <code>R</code> table too! The main functions we will explore here are <code>dplyr</code>’s pipe <code>%&gt;%</code>, <code>select()</code>, <code>filter()</code>, <code>group_by()</code>, <code>summarise()</code> and <code>mutate()</code>.</p>
<div id="select-and-dplyrs-pipe" class="section level3">
<h3><span class="header-section-number">4.2.1</span> select() and dplyr’s pipe</h3>
<p>If, for example, we wanted to move forward with only a few of the variables in our dataframe we could use the <code>select()</code> function. This will keep only the variables you select.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1">koala_select&lt;-<span class="kw">select</span>(koala, species, sex, age)</a></code></pre></div>
<pre><code>##                  species    sex age
## 1 Phascolarctos cinereus   male   8
## 2 Phascolarctos cinereus female  10
## 3 Phascolarctos cinereus   male   1
## 4 Phascolarctos cinereus   male   1
## 5 Phascolarctos cinereus female  10
## 6 Phascolarctos cinereus   male  12</code></pre>
<p>If we open up <code>koala_select</code> we’ll see that it only contains the species, sex and age columns. Above we used ‘normal’ <code>R</code> grammar, but the strengths of dplyr lie in combining several functions using pipes. Since the pipes grammar is unlike anything we’ve seen in R before, let’s repeat what we’ve done above using pipes.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1">koala_select_pipe&lt;-koala<span class="op">%&gt;%</span><span class="kw">select</span>(species, sex, age)</a></code></pre></div>
<p>To help you understand why we wrote that in that way, let’s walk through it step by step. First we summon the koala dataframe and pass it on, using the pipe syntax <code>%&gt;%</code>, to the next step, which is the <code>select()</code> function. In this case we don’t specify which data object we use in the <code>select()</code> function since in gets that from the previous pipe.</p>
</div>
<div id="filter" class="section level3">
<h3><span class="header-section-number">4.2.2</span> filter()</h3>
<p><code>filter()</code> is one of the most useful dplyr functions for data manipulation. Say you’re conducting a study of only male koalas. You won’t need any data on female koalas. So lets get rid of it!</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1">koala_filter&lt;-koala<span class="op">%&gt;%</span><span class="kw">filter</span>(sex <span class="op">==</span><span class="st"> &#39;male&#39;</span>)</a></code></pre></div>
<p>Did it work?</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1"><span class="kw">summary</span>(koala_filter<span class="op">$</span>sex)</a></code></pre></div>
<pre><code>## female   male 
##      0    115</code></pre>
<p>No more females in the data! Let’s test our knowledge with a challenge.</p>
</div>
<div id="challenge-1" class="section level3">
<h3><span class="header-section-number">4.2.3</span> Challenge 1</h3>
<p><strong>Write a single command (which can span multiple lines and includes pipes) that will produce a dataframe that has the values for age, size and color for females only. How many rows and columns does your dataframe have and why?</strong></p>
<p><em>Extra challenge: out of this new dataset, filter only koalas &gt;70cm in size. How many are there?</em></p>
<p>This should be your data structure:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1"><span class="kw">nrow</span>(challenge1)</a></code></pre></div>
<pre><code>## [1] 127</code></pre>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb92-1" title="1"><span class="kw">ncol</span>(challenge1)</a></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>We removed all the males, so our row number reduces from 242 to 127. Then we filter our desired columns and are now at 3 instead of 15.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb94-1" title="1"><span class="kw">nrow</span>(challenge1<span class="fl">.2</span>)</a></code></pre></div>
<pre><code>## [1] 46</code></pre>
<p>You can find the solutions to all challenges posed here at the end of the document. Don’t peek!</p>
</div>
<div id="group_by-and-summarise" class="section level3">
<h3><span class="header-section-number">4.2.4</span> group_by() and summarise()</h3>
<p>Now, we were supposed to be reducing the error prone repetitiveness of what can be done with base R, but up to now we haven’t done that since we would have to repeat the above for each sex. Instead of <code>filter()</code>, which will only pass observations that meet your criteria (in the above: <code>sex=="female"</code>), we can use <code>group_by()</code>, which will essentially use every unique criteria that you could have used in <code>filter()</code>. Let’s see what happens with our data structure when using dplyr’s <code>group_by()</code>.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1">koala_group&lt;-koala<span class="op">%&gt;%</span><span class="kw">group_by</span>(sex)</a>
<a class="sourceLine" id="cb96-2" title="2"></a>
<a class="sourceLine" id="cb96-3" title="3"><span class="kw">str</span>(koala_group)</a></code></pre></div>
<pre><code>## tibble [242 x 15] (S3: grouped_df/tbl_df/tbl/data.frame)
##  $ species: Factor w/ 1 level &quot;Phascolarctos cinereus&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ X      : num [1:242] 153 148 153 153 153 ...
##  $ Y      : num [1:242] -27.5 -22.5 -27.5 -27.5 -27.5 ...
##  $ state  : Factor w/ 4 levels &quot;New South Wales&quot;,..: 2 2 2 2 2 2 2 2 2 2 ...
##  $ region : Factor w/ 2 levels &quot;northern&quot;,&quot;southern&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ sex    : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 2 1 2 2 1 2 2 2 1 1 ...
##  $ weight : num [1:242] 7.12 5.45 6.63 6.47 5.62 ...
##  $ size   : num [1:242] 70.8 70.4 68.7 73 65.2 ...
##  $ fur    : num [1:242] 1.86 1.85 2.48 1.92 1.95 ...
##  $ tail   : num [1:242] 1.17 1.56 1.06 1.8 1.63 ...
##  $ age    : int [1:242] 8 10 1 1 10 12 9 1 1 1 ...
##  $ color  : Factor w/ 6 levels &quot;chocolate brown&quot;,..: 3 4 6 3 4 4 6 4 3 3 ...
##  $ joey   : Factor w/ 2 levels &quot;No&quot;,&quot;Yes&quot;: 1 2 1 1 1 1 1 1 1 1 ...
##  $ behav  : Factor w/ 3 levels &quot;Feeding&quot;,&quot;Just Chillin&quot;,..: 3 3 2 3 3 1 2 3 1 3 ...
##  $ obs    : Factor w/ 3 levels &quot;Opportunistic&quot;,..: 2 1 2 3 3 1 3 2 2 2 ...
##  - attr(*, &quot;groups&quot;)= tibble [2 x 2] (S3: tbl_df/tbl/data.frame)
##   ..$ sex  : Factor w/ 2 levels &quot;female&quot;,&quot;male&quot;: 1 2
##   ..$ .rows:List of 2
##   .. ..$ : int [1:127] 2 5 9 10 12 13 15 17 20 22 ...
##   .. ..$ : int [1:115] 1 3 4 6 7 8 11 14 16 18 ...
##   ..- attr(*, &quot;.drop&quot;)= logi TRUE</code></pre>
<p>You will notice that the structure of the dataframe where we used <code>group_by()</code> (<code>koala_group</code>) is not the same as the original <code>koala</code> dataset. A grouped dataset can be thought of as a list where each item in the list is a data.frame which contains only the rows that correspond to the a particular value ‘Sex’ (at least in the example above).</p>
<p>The above was a bit on the uneventful side because <code>group_by()</code> is only really useful in conjunction with <code>summarise()</code>. This will allow you to create new variable(s) by using functions that repeat for each of the sex-specific data frames. That is to say, using the <code>group_by()</code> function, we split our original dataframe into multiple pieces, then we can run functions such as <code>mean()</code> or <code>sd()</code> within <code>summarise()</code>:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1">koala_group_sum&lt;-koala<span class="op">%&gt;%</span><span class="kw">group_by</span>(sex)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb98-2" title="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_age=</span><span class="kw">mean</span>(age))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   sex    mean_age
##   &lt;fct&gt;     &lt;dbl&gt;
## 1 female     6.25
## 2 male       6.63</code></pre>
<p>And there we go. We got what we wanted and summarised the mean age of our koalas for both sexes separately. And we did that using only one simple line of code! I think it is time for another challenge to test our skills!</p>
</div>
<div id="challenge-2" class="section level3">
<h3><span class="header-section-number">4.2.5</span> Challenge 2</h3>
<p><strong>Calculate the average weight value per state and Sex. Which combination of state and sex has the heaviest and which combination had the lightest koalas?</strong></p>
<pre><code>## # A tibble: 8 x 3
## # Groups:   state [4]
##   state           sex    mean_weight
##   &lt;fct&gt;           &lt;fct&gt;        &lt;dbl&gt;
## 1 New South Wales female        6.54
## 2 New South Wales male          9.07
## 3 Queensland      female        5.68
## 4 Queensland      male          6.82
## 5 South Australia female        7.59
## 6 South Australia male         16.8 
## 7 Victoria        female        7.58
## 8 Victoria        male          7.48</code></pre>
<p>That is already quite powerful, but it gets even better! You’re not limited to defining only one new variable in <code>summarise()</code>:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1">challenge2_ext&lt;-koala<span class="op">%&gt;%</span><span class="kw">group_by</span>(state, sex)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb101-2" title="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight),</a>
<a class="sourceLine" id="cb101-3" title="3">            <span class="dt">sd_weight =</span> <span class="kw">sd</span>(weight),</a>
<a class="sourceLine" id="cb101-4" title="4">            <span class="dt">sample_no =</span> <span class="kw">n</span>())</a></code></pre></div>
<p>We can create a new dataframe with as many new variables as we want. Very useful for our initial data exploration! Let’s get our hands another very useful function: <code>mutate()</code>.</p>
</div>
<div id="mutate" class="section level3">
<h3><span class="header-section-number">4.2.6</span> mutate()</h3>
<p>We can create an entirely new variables in our initial dataset prior to (or even after) summarizing information using <code>mutate()</code>. Let’s say we’re interested in the weight:size ratio of our Koalas. Also we want to give each individual a numeric identifier to be able to better work with our data later on.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1">koala_mutate&lt;-koala<span class="op">%&gt;%</span><span class="kw">mutate</span>(<span class="dt">weight_size_ratio =</span> size<span class="op">/</span>weight, <span class="dt">ID =</span> <span class="kw">row_number</span>())</a></code></pre></div>
<pre><code>##  [1] &quot;species&quot;           &quot;X&quot;                 &quot;Y&quot;                
##  [4] &quot;state&quot;             &quot;region&quot;            &quot;sex&quot;              
##  [7] &quot;weight&quot;            &quot;size&quot;              &quot;fur&quot;              
## [10] &quot;tail&quot;              &quot;age&quot;               &quot;color&quot;            
## [13] &quot;joey&quot;              &quot;behav&quot;             &quot;obs&quot;              
## [16] &quot;weight_size_ratio&quot; &quot;ID&quot;</code></pre>
<p>Our dataset now has two extra columns containing the variables we were interested in. If you do not want to manipulate your raw data, you can use mutate before grouping and summarising to create the summary table straight away:</p>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb104-1" title="1">koala_mutate_weight_size&lt;-koala<span class="op">%&gt;%</span><span class="kw">mutate</span>(<span class="dt">weight_size_ratio =</span> size<span class="op">/</span>weight)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb104-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(sex)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb104-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight),</a>
<a class="sourceLine" id="cb104-4" title="4">            <span class="dt">sd_weight =</span> <span class="kw">sd</span>(weight),</a>
<a class="sourceLine" id="cb104-5" title="5">            <span class="dt">mean_weight_size =</span> <span class="kw">mean</span> (weight_size_ratio),</a>
<a class="sourceLine" id="cb104-6" title="6">            <span class="dt">max_weight_size =</span> <span class="kw">max</span>(weight_size_ratio))</a></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   sex    mean_weight sd_weight mean_weight_size max_weight_size
##   &lt;fct&gt;        &lt;dbl&gt;     &lt;dbl&gt;            &lt;dbl&gt;           &lt;dbl&gt;
## 1 female        6.67     0.533            10.4             12.9
## 2 male          9.31     2.38              8.21            11.9</code></pre>
<p>Great! Let’s end the lesson with another challenge, combining all the functions we have looked at today.</p>
</div>
<div id="challenge-3" class="section level3">
<h3><span class="header-section-number">4.2.7</span> Challenge 3</h3>
<p><strong>Calculate the average tail length and fur thickness for a group of 20 randomly selected males and females from New South Wales. Then arrange the mean tail length in descending order.</strong></p>
<p><em>Hint: Use the dplyr functions</em> <code>arrange()</code> <em>and</em> <code>sample_n()</code><em>, they have similar syntax to other dplyr functions. Look at the help by calling ‘?function’, e.g.</em> <code>?arrange</code><em>.</em></p>
<pre><code>## # A tibble: 2 x 3
##   sex    mean_tail mean_fur
##   &lt;fct&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1 male        1.52     2.97
## 2 female      1.46     2.47</code></pre>
<p>Since we are sampling randomly, these will look different for each of you.</p>
</div>
<div id="pivoting" class="section level3">
<h3><span class="header-section-number">4.2.8</span> Pivoting</h3>
<p>Another really useful processing option when manipulating or re-arranging data is pivoting, especially when you come from an Microsoft Excel background. For this, a bit of knowledge on <em>tidy</em> data is required. When we process data in <code>R</code>, it is extremely beneficial to have a long dataset, which we call <em>tidy</em>. These type of data follow three principles:</p>
<ol style="list-style-type: decimal">
<li>Variables make up our columns</li>
<li>Observations are in the rows</li>
<li>Values are in the cells</li>
</ol>
<p>Our koala dataset is an example of <em>tidy</em> data. Let’s reduce our dataset to make an example:</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1">koala_subsample&lt;-koala<span class="op">%&gt;%</span><span class="kw">select</span>(species, region, sex, tail, age)</a>
<a class="sourceLine" id="cb107-2" title="2"></a>
<a class="sourceLine" id="cb107-3" title="3"><span class="kw">head</span>(koala_subsample)</a></code></pre></div>
<pre><code>##                  species   region    sex     tail age
## 1 Phascolarctos cinereus northern   male 1.168241   8
## 2 Phascolarctos cinereus northern female 1.562456  10
## 3 Phascolarctos cinereus northern   male 1.056640   1
## 4 Phascolarctos cinereus northern   male 1.801244   1
## 5 Phascolarctos cinereus northern female 1.625600  10
## 6 Phascolarctos cinereus northern   male 1.086675  12</code></pre>
<p><em>Tidy</em> datasets, are also called <em>indexed</em> dataset. We can look up a measure using both region and sex as an index (like when we were grouping before). Let’s assume we collect another measure of tail-length on another visit to our sites. In data-entry manner, this would probably go into another column:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1">koala_subsample&lt;-koala_subsample<span class="op">%&gt;%</span><span class="kw">mutate</span>(<span class="dt">tail2 =</span> <span class="kw">runif</span>(<span class="kw">nrow</span>(koala_subsample), <span class="dt">min =</span> <span class="dv">2</span>, <span class="dt">max =</span> <span class="dv">3</span>))</a>
<a class="sourceLine" id="cb109-2" title="2"></a>
<a class="sourceLine" id="cb109-3" title="3"><span class="kw">head</span>(koala_subsample)</a></code></pre></div>
<pre><code>##                  species   region    sex     tail age    tail2
## 1 Phascolarctos cinereus northern   male 1.168241   8 2.390985
## 2 Phascolarctos cinereus northern female 1.562456  10 2.886624
## 3 Phascolarctos cinereus northern   male 1.056640   1 2.471714
## 4 Phascolarctos cinereus northern   male 1.801244   1 2.787553
## 5 Phascolarctos cinereus northern female 1.625600  10 2.190224
## 6 Phascolarctos cinereus northern   male 1.086675  12 2.050512</code></pre>
<p>Our table is now wide, because we added a variable, that is not indexed. This can cause problems, especially when we want to visualize these two measurements. We will introduce <code>ggplot2</code> for visualizing in later tutorials, but here is just a basic boxplot</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1"><span class="kw">ggplot</span>(koala_subsample, <span class="kw">aes</span>(<span class="dt">x=</span>species, <span class="dt">y=</span>tail)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb111-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-dplyr_tut-github_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1"><span class="kw">ggplot</span>(koala_subsample, <span class="kw">aes</span>(<span class="dt">x=</span>species, <span class="dt">y=</span>tail2)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb112-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-dplyr_tut-github_files/figure-html/unnamed-chunk-29-2.png" width="672" /></p>
<p>We can plot either column, but not both. Nevertheless, we can use another column that is already in long format, to separate the boxes:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1"><span class="kw">ggplot</span>(koala_subsample, <span class="kw">aes</span>(<span class="dt">x=</span>species, <span class="dt">y=</span>tail, <span class="dt">fill =</span> region)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb113-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-dplyr_tut-github_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Southern koalas have shorter tails, interesting :) If we want to compare our two measurements though, we need them in one column, and that is where pivoting comes in handy:</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb114-1" title="1">koala_pivot&lt;-koala_subsample<span class="op">%&gt;%</span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">c</span>(tail, tail2), <span class="dt">names_to =</span> <span class="st">&#39;tail_measure&#39;</span>, <span class="dt">values_to =</span> <span class="st">&#39;tail_length&#39;</span>)</a>
<a class="sourceLine" id="cb114-2" title="2"></a>
<a class="sourceLine" id="cb114-3" title="3"><span class="kw">head</span>(koala_pivot)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   species                region   sex      age tail_measure tail_length
##   &lt;fct&gt;                  &lt;fct&gt;    &lt;fct&gt;  &lt;int&gt; &lt;chr&gt;              &lt;dbl&gt;
## 1 Phascolarctos cinereus northern male       8 tail                1.17
## 2 Phascolarctos cinereus northern male       8 tail2               2.39
## 3 Phascolarctos cinereus northern female    10 tail                1.56
## 4 Phascolarctos cinereus northern female    10 tail2               2.89
## 5 Phascolarctos cinereus northern male       1 tail                1.06
## 6 Phascolarctos cinereus northern male       1 tail2               2.47</code></pre>
<p>We create the index column <code>tail_measure</code> to address our two measurements. The column containing the measurements is now called <code>tail_length</code>. Let’s see what has changed between the first and second measurement:</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1"><span class="kw">ggplot</span>(koala_pivot, <span class="kw">aes</span>(<span class="dt">x=</span>species, <span class="dt">y=</span>tail_length, <span class="dt">fill =</span> tail_measure)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb116-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="03-dplyr_tut-github_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<p>Wow, seems the tails have grown a lot in the past ;) We can also facet to check both the different measures and the genders:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1"><span class="kw">ggplot</span>(koala_pivot, <span class="kw">aes</span>(<span class="dt">x=</span>species, <span class="dt">y=</span>tail_length, <span class="dt">fill =</span> tail_measure)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb117-2" title="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()<span class="op">+</span></a>
<a class="sourceLine" id="cb117-3" title="3"><span class="st">  </span><span class="kw">facet_grid</span>(<span class="op">~</span>sex)</a></code></pre></div>
<p><img src="03-dplyr_tut-github_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>Great, now we know how to make our dataset long and thus <em>tidy</em>!</p>
<p>Let’s create a dataset for you to practice:</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1">koala_subsample2&lt;-koala<span class="op">%&gt;%</span><span class="kw">select</span>(species, region, sex, age, tail, joey,)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb118-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age2 =</span> age<span class="op">+</span><span class="kw">sample</span>(<span class="dv">3</span>, <span class="kw">nrow</span>(koala_subsample), <span class="dt">replace =</span> T),</a>
<a class="sourceLine" id="cb118-3" title="3">         <span class="dt">tail2 =</span> <span class="kw">runif</span>(<span class="kw">nrow</span>(koala_subsample), <span class="dt">min =</span> <span class="dv">2</span>, <span class="dt">max =</span> <span class="dv">3</span>),</a>
<a class="sourceLine" id="cb118-4" title="4">         <span class="dt">tail3 =</span> <span class="kw">runif</span>(<span class="kw">nrow</span>(koala_subsample), <span class="dt">min =</span> <span class="dv">1</span>, <span class="dt">max =</span> <span class="fl">1.5</span>),</a>
<a class="sourceLine" id="cb118-5" title="5">         <span class="dt">joey2 =</span> <span class="kw">ifelse</span>(koala<span class="op">$</span>sex <span class="op">==</span><span class="st"> &#39;female&#39;</span>,</a>
<a class="sourceLine" id="cb118-6" title="6">                              <span class="kw">sample</span>(<span class="kw">c</span>(<span class="st">&#39;Yes&#39;</span>, <span class="st">&#39;No&#39;</span>), <span class="kw">nrow</span>(koala),  <span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.7</span>), <span class="dt">replace =</span> T), <span class="st">&#39;No&#39;</span>),</a>
<a class="sourceLine" id="cb118-7" title="7">         <span class="dt">joey3 =</span> <span class="kw">ifelse</span>(koala<span class="op">$</span>sex <span class="op">==</span><span class="st"> &#39;female&#39;</span>,</a>
<a class="sourceLine" id="cb118-8" title="8">                              <span class="kw">sample</span>(<span class="kw">c</span>(<span class="st">&#39;Yes&#39;</span>, <span class="st">&#39;No&#39;</span>), <span class="kw">nrow</span>(koala),  <span class="dt">prob=</span><span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>), <span class="dt">replace =</span> T), <span class="st">&#39;No&#39;</span>),)</a>
<a class="sourceLine" id="cb118-9" title="9"></a>
<a class="sourceLine" id="cb118-10" title="10"><span class="kw">head</span>(koala_subsample2)</a></code></pre></div>
<pre><code>##                  species   region    sex age     tail joey age2    tail2
## 1 Phascolarctos cinereus northern   male   8 1.168241   No   10 2.321813
## 2 Phascolarctos cinereus northern female  10 1.562456  Yes   12 2.515060
## 3 Phascolarctos cinereus northern   male   1 1.056640   No    4 2.054489
## 4 Phascolarctos cinereus northern   male   1 1.801244   No    3 2.330572
## 5 Phascolarctos cinereus northern female  10 1.625600   No   11 2.626772
## 6 Phascolarctos cinereus northern   male  12 1.086675   No   14 2.672318
##      tail3 joey2 joey3
## 1 1.340993    No    No
## 2 1.134595    No   Yes
## 3 1.339913    No    No
## 4 1.278094    No    No
## 5 1.311311    No   Yes
## 6 1.073392    No    No</code></pre>
<p>So we continued our measurements over 3 years, each koala aged 1-3 years which is expressed in the <code>age2</code> column. When we revisited, we took additional measurements of tail length, and checked weather females had a joey. Can you <em>tidy</em> up this table?</p>
</div>
<div id="challenge-4" class="section level3">
<h3><span class="header-section-number">4.2.9</span> Challenge 4</h3>
<p><strong>To make the changes more visible, give each individual an ID that describes the individual using <code>mutatue()</code>, as we did before. It’s easiest in steps! Refer to <code>?pivot_longer</code> for help. Please sort the dataset as follows in the end: species, region, sex, all thew index columns, all measurement columns.</strong></p>
<pre><code>## # A tibble: 6 x 10
##      ID species region sex   age_check tail_measure joey_check   age  tail
##   &lt;int&gt; &lt;fct&gt;   &lt;fct&gt;  &lt;fct&gt; &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt;      &lt;int&gt; &lt;dbl&gt;
## 1     1 Phasco~ north~ male  age       tail         joey           8  1.17
## 2     1 Phasco~ north~ male  age       tail         joey2          8  1.17
## 3     1 Phasco~ north~ male  age       tail         joey3          8  1.17
## 4     1 Phasco~ north~ male  age       tail2        joey           8  2.32
## 5     1 Phasco~ north~ male  age       tail2        joey2          8  2.32
## 6     1 Phasco~ north~ male  age       tail2        joey3          8  2.32
## # ... with 1 more variable: joey &lt;chr&gt;</code></pre>
<p>With this meany measurements, we can illustrate the long table format well. Each individual now has 18 rows, because our maximum measurement was 3x3 for joey and tail. Each ID number is one koala.</p>
<p>You can easily reverse your changes using <code>pivot_wider()</code>. Let’s reverse the age changes:</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" title="1">koala_pivot_wide&lt;-koala_pivot_subsample<span class="op">%&gt;%</span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> age_check, <span class="dt">values_from =</span> age)</a>
<a class="sourceLine" id="cb121-2" title="2"></a>
<a class="sourceLine" id="cb121-3" title="3"><span class="kw">head</span>(koala_pivot_wide)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 10
##      ID species region sex   tail_measure joey_check  tail joey    age
##   &lt;int&gt; &lt;fct&gt;   &lt;fct&gt;  &lt;fct&gt; &lt;chr&gt;        &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;int&gt;
## 1     1 Phasco~ north~ male  tail         joey        1.17 No        8
## 2     1 Phasco~ north~ male  tail         joey2       1.17 No        8
## 3     1 Phasco~ north~ male  tail         joey3       1.17 No        8
## 4     1 Phasco~ north~ male  tail2        joey        2.32 No        8
## 5     1 Phasco~ north~ male  tail2        joey2       2.32 No        8
## 6     1 Phasco~ north~ male  tail2        joey3       2.32 No        8
## # ... with 1 more variable: age2 &lt;int&gt;</code></pre>
<p>Having each variable in a separate column is important e.g. in modeling, when you have to specify you predictor variables by column. Let’s practice <code>pivot_wider()</code> with some made-up koala data data:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" title="1">new_data&lt;-<span class="kw">rbind</span>(<span class="kw">cbind.data.frame</span>(<span class="dt">ID =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">40</span>, <span class="dt">sex =</span> <span class="st">&#39;male&#39;</span>, </a>
<a class="sourceLine" id="cb123-2" title="2">                                 <span class="dt">measurement =</span> <span class="kw">c</span>(<span class="st">&#39;tail1&#39;</span>, <span class="st">&#39;tail2&#39;</span>, <span class="st">&#39;tail3&#39;</span>, <span class="st">&#39;tail4&#39;</span>)),</a>
<a class="sourceLine" id="cb123-3" title="3">                <span class="kw">cbind.data.frame</span>(<span class="dt">ID =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">40</span>, <span class="dt">sex =</span> <span class="st">&#39;female&#39;</span>,</a>
<a class="sourceLine" id="cb123-4" title="4">                                 <span class="dt">measurement =</span> <span class="kw">c</span>(<span class="st">&#39;tail1&#39;</span>, <span class="st">&#39;tail2&#39;</span>, <span class="st">&#39;tail3&#39;</span>, <span class="st">&#39;tail4&#39;</span>)))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb123-5" title="5"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">tail =</span> <span class="kw">runif</span>(<span class="dv">80</span>, <span class="dt">min =</span> <span class="dv">1</span>, <span class="dt">max =</span> <span class="dv">2</span>), <span class="dt">animal =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>), <span class="dt">each =</span> <span class="dv">4</span>))</a>
<a class="sourceLine" id="cb123-6" title="6"></a>
<a class="sourceLine" id="cb123-7" title="7"><span class="kw">head</span>(new_data)</a></code></pre></div>
<pre><code>##   ID  sex measurement     tail animal
## 1  1 male       tail1 1.991282      1
## 2  2 male       tail2 1.509559      1
## 3  3 male       tail3 1.683454      1
## 4  4 male       tail4 1.723617      1
## 5  5 male       tail1 1.255344      2
## 6  6 male       tail2 1.076020      2</code></pre>
</div>
<div id="challenge-5" class="section level3">
<h3><span class="header-section-number">4.2.10</span> Challenge 5</h3>
<p><strong><em>Create a wide dataset with one column per tail measurement, add an individual ID for each koala. Which column do you need to remove for this to work?</em></strong></p>
<pre><code>## # A tibble: 6 x 6
##   sex   animal tail1 tail2 tail3 tail4
##   &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 male       1  1.99  1.51  1.68  1.72
## 2 male       2  1.26  1.08  1.46  1.83
## 3 male       3  1.37  1.65  1.10  1.65
## 4 male       4  1.37  1.75  1.06  1.76
## 5 male       5  1.19  1.93  1.51  1.53
## 6 male       6  1.42  1.53  2.00  1.10</code></pre>
<p>Good job on all this! Let’s move on to data visualization using <code>ggplot2</code> :)</p>
</div>
<div id="solution-to-all-challenges" class="section level3">
<h3><span class="header-section-number">4.2.11</span> Solution to all challenges</h3>
<div id="challenge-1-1" class="section level4">
<h4><span class="header-section-number">4.2.11.1</span> Challenge 1</h4>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1">challenge1&lt;-koala<span class="op">%&gt;%</span><span class="kw">filter</span>(sex <span class="op">==</span><span class="st"> &#39;female&#39;</span>)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb126-2" title="2"><span class="st">  </span><span class="kw">select</span>(age, size, color)</a></code></pre></div>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1">challenge1<span class="fl">.2</span>&lt;-challenge1<span class="op">%&gt;%</span><span class="kw">filter</span>(size<span class="op">&gt;</span><span class="dv">70</span>)</a></code></pre></div>
</div>
<div id="challenge-2-1" class="section level4">
<h4><span class="header-section-number">4.2.11.2</span> Challenge 2</h4>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1">challenge2&lt;-koala<span class="op">%&gt;%</span><span class="kw">group_by</span>(state, sex)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb128-2" title="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_weight =</span> <span class="kw">mean</span>(weight))</a></code></pre></div>
</div>
<div id="challenge-3-1" class="section level4">
<h4><span class="header-section-number">4.2.11.3</span> Challenge 3</h4>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" title="1">challenge3&lt;-koala<span class="op">%&gt;%</span><span class="kw">filter</span>(state <span class="op">==</span><span class="st"> &#39;New South Wales&#39;</span>)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb129-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(sex)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb129-3" title="3"><span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">20</span>)<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb129-4" title="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_tail =</span> <span class="kw">mean</span>(tail), <span class="dt">mean_fur =</span> <span class="kw">mean</span>(fur))<span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb129-5" title="5"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(mean_tail))</a></code></pre></div>
</div>
<div id="challenge-4-1" class="section level4">
<h4><span class="header-section-number">4.2.11.4</span> Challenge 4</h4>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">koala_pivot_subsample&lt;-koala_subsample2<span class="op">%&gt;%</span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">c</span>(age, age2), <span class="dt">names_to =</span> <span class="st">&#39;age_check&#39;</span>, <span class="dt">values_to =</span> <span class="st">&#39;age&#39;</span>)</a>
<a class="sourceLine" id="cb130-2" title="2"></a>
<a class="sourceLine" id="cb130-3" title="3">koala_pivot_subsample&lt;-koala_pivot_subsample<span class="op">%&gt;%</span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">c</span>(tail, tail2, tail3), <span class="dt">names_to =</span> <span class="st">&#39;tail_measure&#39;</span>, <span class="dt">values_to =</span> <span class="st">&#39;tail&#39;</span>)</a>
<a class="sourceLine" id="cb130-4" title="4"></a>
<a class="sourceLine" id="cb130-5" title="5">koala_pivot_subsample&lt;-koala_pivot_subsample<span class="op">%&gt;%</span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">c</span>(joey, joey2, joey3), <span class="dt">names_to =</span> <span class="st">&#39;joey_check&#39;</span>, <span class="dt">values_to =</span> <span class="st">&#39;joey&#39;</span>)</a>
<a class="sourceLine" id="cb130-6" title="6"></a>
<a class="sourceLine" id="cb130-7" title="7">koala_pivot_subsample&lt;-koala_pivot_subsample<span class="op">%&gt;%</span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">5</span>,<span class="dv">7</span>,<span class="dv">9</span>) <span class="co">#instead of typing the names you can use the column number!</span></a></code></pre></div>
</div>
<div id="challenge-5-1" class="section level4">
<h4><span class="header-section-number">4.2.11.5</span> Challenge 5</h4>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1">new_data_wide&lt;-new_data<span class="op">%&gt;%</span><span class="kw">select</span>(<span class="op">-</span>ID)<span class="op">%&gt;%</span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> measurement, <span class="dt">values_from =</span> tail)</a></code></pre></div>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducing-the-koala-dataset.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="introduction-to-data-visualization-in-ggplot2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
